spring:
  config:
    activate:
      on-profile:
        - test
  datasource:
    #h2
    url: jdbc:h2:mem:atm
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: create        # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    sql: off
    root: info
    com.zaxxer.hikari: ERROR
    org.hibernate.orm.jdbc.bind: trace

server:
  port: 8080